apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-planner-secret
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.secrets.REDIS_PASSWORD | b64enc | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.MINIO_ACCESS_KEY | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.MINIO_SECRET_KEY | b64enc | quote }}