replicaCount: 2

image:
  repository: order-service
  pullPolicy: Never
  tag: "v10"

config:
  POSTGRES_HOST: "host.minikube.internal"
  REDIS_HOST: "host.minikube.internal"
  KAFKA_SERVER: "host.minikube.internal"
  KAFKA_PORT: "29092"
  MINIO_HOST: "http://host.minikube.internal:9000"
  ROVER_HOST: "rover-service-rover-service"
  MISSION_HOST: "mission-service-mission-service"

secrets:
  POSTGRES_USERNAME: "citus"
  POSTGRES_PASSWORD: "citus_password"
  REDIS_PASSWORD: "redis_password"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi