apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rover-service
  labels:
    app: rover-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: rover-service