apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mission-secret
type: Opaque
data:
  POSTGRES_USERNAME: {{ .Values.secrets.POSTGRES_USERNAME | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | b64enc | quote }}