spring:
  application:
    name: rover-facade
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: ${REDIS_PASSWORD:redis_password}
      connect-timeout: 2s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost}:${KAFKA_PORT:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: rover-facade-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    url: jdbc:clickhouse://${CLICKHOUSE_HOST:localhost}:8123/telemetry_db
    username: ${CLICKHOUSE_USERNAME:default}
    password: ${CLICKHOUSE_PASSWORD:ch_password}
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

mqtt:
  broker-url: tcp://${MQTT_HOST:localhost}:1883
  client-id: backend-facade-${random.uuid}