replicaCount: 1

image:
  repository: planner-global
  pullPolicy: Never
  tag: "v9"

config:
  KAFKA_SERVER: "host.minikube.internal"
  KAFKA_PORT: "29092"
  REDIS_HOST: "host.minikube.internal"
  MINIO_HOST: "http://host.minikube.internal:9000"

secrets:
  REDIS_PASSWORD: "redis_password"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2048Mi