apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-order-config
data:
  POSTGRES_HOST: {{ .Values.config.POSTGRES_HOST | quote }}
  REDIS_HOST: {{ .Values.config.REDIS_HOST | quote }}
  KAFKA_SERVER: {{ .Values.config.KAFKA_SERVER | quote }}
  KAFKA_PORT: {{ .Values.config.KAFKA_PORT | quote }}
  MINIO_HOST: {{ .Values.config.MINIO_HOST | quote }}
  ROVER_HOST: {{ .Values.config.ROVER_HOST | quote }}
  MISSION_HOST: {{ .Values.config.MISSION_HOST | quote }}