apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-order-service
  labels:
    app: order-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-order-config
            - secretRef:
                name: {{ .Release.Name }}-order-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}