apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-routing-service
  labels:
    app: routing-service-{{ .Values.config.REGION_ID }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: routing-service-{{ .Values.config.REGION_ID }}
  template:
    metadata:
      labels:
        app: routing-service-{{ .Values.config.REGION_ID }}
    spec:
      containers:
        - name: routing-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 9090
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-routing-config
            - secretRef:
                name: {{ .Release.Name }}-routing-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}