replicaCount: 1

image:
  repository: rover-service
  pullPolicy: Never
  tag: "v5"

config:
  POSTGRES_HOST: "host.minikube.internal"
  KAFKA_SERVER: "host.minikube.internal"
  KAFKA_PORT: "29092"
  REDIS_HOST: "host.minikube.internal"

secrets:
  POSTGRES_USERNAME: "admin"
  POSTGRES_PASSWORD: "admin_password"
  REDIS_PASSWORD: "redis_password"

service:
  type: ClusterIP
  port: 8080
  grpcPort: 9090

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi